export const translations = {
  en: {
    appTitle: "AI Medical Diagnosis Assistant",
    appSubtitle: "Rural Healthcare Support System",
    
    // Navigation
    newPatient: "New Patient",
    diagnose: "Diagnose",
    history: "History",
    patients: "Patients",
    
    // Patient Form
    patientRegistration: "Patient Registration",
    patientName: "Patient Name",
    age: "Age",
    sex: "Sex",
    male: "Male",
    female: "Female",
    other: "Other",
    weight: "Weight (kg)",
    village: "Village",
    phone: "Phone Number",
    registerPatient: "Register Patient",
    
    // Diagnosis Form
    selectPatient: "Select Patient",
    searchPatient: "Search patient...",
    symptoms: "Symptoms",
    symptomsPlaceholder: "Describe symptoms in detail (e.g., fever, cough, headache, body pain...)",
    vitals: "Vital Signs",
    temperature: "Temperature (°F)",
    bloodPressure: "Blood Pressure",
    systolic: "Systolic",
    diastolic: "Diastolic",
    spo2: "SpO2 (%)",
    pulse: "Pulse (bpm)",
    diagnoseNow: "Diagnose Now",
    analyzing: "Analyzing...",
    
    // Results
    diagnosisResults: "Diagnosis Results",
    topDiagnoses: "Top Differential Diagnoses",
    confidence: "Confidence",
    redFlags: "⚠️ Red Flag Alerts",
    triageInstructions: "Triage Instructions",
    medications: "Suggested Medications",
    contraindications: "Contraindications & Warnings",
    drugInteractionCheck: "Drug Interaction Check",
    
    // Disclaimer
    disclaimer: "Medical Disclaimer",
    disclaimerText: "This is an AI-assisted diagnostic tool for healthcare workers. It is NOT a substitute for professional medical judgment. Always verify diagnoses and treatment plans with qualified medical personnel. In emergencies, refer immediately to higher medical facilities.",
    
    // Common
    save: "Save",
    cancel: "Cancel",
    back: "Back",
    next: "Next",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    
    // Messages
    patientRegistered: "Patient registered successfully",
    diagnosisSaved: "Diagnosis saved successfully",
    errorOccurred: "An error occurred. Please try again.",
    noResultsFound: "No results found",
    
    // History
    encounterHistory: "Encounter History",
    date: "Date",
    diagnosis: "Diagnosis",
    diagnoses: "Diagnoses",
    viewDetails: "View Details",
    searchPatients: "Search by patient name, symptoms, or village...",
    noEncountersYet: "No encounters recorded yet",
    viewHistory: "View History",
    
    // Patient Profile
    patientProfile: "Patient Profile",
    totalEncounters: "Total Encounters",
    viewProfile: "View Profile",
    allEncounters: "All Encounters",
    
    // Print
    printReport: "Print Report",
    patientInformation: "Patient Information",
    vitalSigns: "Vital Signs",
    clinicalFindings: "Clinical Findings",
    assessmentAndPlan: "Assessment and Plan",
    medicalDisclaimer: "Medical Disclaimer",
    generatedBy: "Generated by AI Medical Diagnosis Assistant",
    dateTime: "Date & Time",
    
    // Home Page
    homeSubtitle: "AI-powered diagnostic support for rural healthcare workers",
    homeDescription: "This system uses advanced AI models running locally in your browser to provide instant diagnostic assistance, triage recommendations, and treatment guidelines for common rural health conditions.",
    features: "Features:",
    featureOfflineAI: "Offline AI diagnosis after initial setup",
    featureRedFlags: "Red flag vital signs alerts",
    featureTriage: "Triage recommendations",
    featureDrugInteraction: "Drug interaction warnings",
    featureMultilingual: "Multilingual (English, Hindi & Bangla)",
    featurePatientRecords: "Patient records management",
    
    // Authentication
    login: "Login",
    loginDescription: "Enter your credentials to access the system",
    logout: "Logout",
    email: "Email",
    password: "Password",
    username: "Username",
    fullName: "Full Name",
    role: "Role",
    userRole: "User",
    adminRole: "Admin",
    
    // Admin Panel
    createUser: "Create New User",
    createUserDescription: "Add a new healthcare worker to the system",
    creating: "Creating...",
    users: "Users",
    manageUsers: "Manage healthcare workers",
    actions: "Actions",
    adminPanel: "Admin Panel",
  },
  hi: {
    appTitle: "एआई चिकित्सा निदान सहायक",
    appSubtitle: "ग्रामीण स्वास्थ्य सेवा प्रणाली",
    
    // Navigation
    newPatient: "नया मरीज",
    diagnose: "निदान",
    history: "इतिहास",
    patients: "मरीज",
    
    // Patient Form
    patientRegistration: "मरीज पंजीकरण",
    patientName: "मरीज का नाम",
    age: "उम्र",
    sex: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    weight: "वजन (किलो)",
    village: "गांव",
    phone: "फोन नंबर",
    registerPatient: "मरीज पंजीकृत करें",
    
    // Diagnosis Form
    selectPatient: "मरीज चुनें",
    searchPatient: "मरीज खोजें...",
    symptoms: "लक्षण",
    symptomsPlaceholder: "लक्षणों का विस्तार से वर्णन करें (जैसे, बुखार, खांसी, सिर दर्द, शरीर में दर्द...)",
    vitals: "महत्वपूर्ण संकेत",
    temperature: "तापमान (°F)",
    bloodPressure: "रक्तचाप",
    systolic: "सिस्टोलिक",
    diastolic: "डायस्टोलिक",
    spo2: "SpO2 (%)",
    pulse: "नाड़ी (bpm)",
    diagnoseNow: "अभी निदान करें",
    analyzing: "विश्लेषण हो रहा है...",
    
    // Results
    diagnosisResults: "निदान परिणाम",
    topDiagnoses: "शीर्ष विभेदक निदान",
    confidence: "विश्वास स्तर",
    redFlags: "⚠️ खतरे की चेतावनी",
    triageInstructions: "ट्राइएज निर्देश",
    medications: "सुझाई गई दवाएं",
    contraindications: "प्रतिबंध और चेतावनियां",
    drugInteractionCheck: "दवा परस्पर क्रिया जांच",
    
    // Disclaimer
    disclaimer: "चिकित्सा अस्वीकरण",
    disclaimerText: "यह स्वास्थ्य कर्मियों के लिए एक एआई-सहायक निदान उपकरण है। यह पेशेवर चिकित्सा निर्णय का विकल्प नहीं है। हमेशा योग्य चिकित्सा कर्मियों से निदान और उपचार योजनाओं को सत्यापित करें। आपात स्थिति में, तुरंत उच्च चिकित्सा सुविधाओं को संदर्भित करें।",
    
    // Common
    save: "सहेजें",
    cancel: "रद्द करें",
    back: "वापस",
    next: "अगला",
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    success: "सफलता",
    
    // Messages
    patientRegistered: "मरीज सफलतापूर्वक पंजीकृत",
    diagnosisSaved: "निदान सफलतापूर्वक सहेजा गया",
    errorOccurred: "एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    noResultsFound: "कोई परिणाम नहीं मिला",
    
    // History
    encounterHistory: "मुलाकात इतिहास",
    date: "तारीख",
    diagnosis: "निदान",
    diagnoses: "निदान",
    viewDetails: "विवरण देखें",
    searchPatients: "रोगी के नाम, लक्षण, या गांव से खोजें...",
    noEncountersYet: "अभी तक कोई मुलाकात दर्ज नहीं की गई",
    viewHistory: "इतिहास देखें",
    
    // Patient Profile
    patientProfile: "रोगी प्रोफ़ाइल",
    totalEncounters: "कुल मुलाकातें",
    viewProfile: "प्रोफ़ाइल देखें",
    allEncounters: "सभी मुलाकातें",
    
    // Print
    printReport: "रिपोर्ट प्रिंट करें",
    patientInformation: "रोगी की जानकारी",
    vitalSigns: "महत्वपूर्ण संकेत",
    clinicalFindings: "नैदानिक निष्कर्ष",
    assessmentAndPlan: "मूल्यांकन और योजना",
    medicalDisclaimer: "चिकित्सा अस्वीकरण",
    generatedBy: "एआई चिकित्सा निदान सहायक द्वारा उत्पन्न",
    dateTime: "दिनांक और समय",
    
    // Home Page
    homeSubtitle: "ग्रामीण स्वास्थ्य कर्मियों के लिए एआई-संचालित निदान सहायता",
    homeDescription: "यह प्रणाली आम ग्रामीण स्वास्थ्य स्थितियों के लिए तत्काल निदान सहायता, ट्राइएज सिफारिशें और उपचार दिशानिर्देश प्रदान करने के लिए आपके ब्राउज़र में स्थानीय रूप से चलने वाले उन्नत एआई मॉडल का उपयोग करती है।",
    features: "विशेषताएँ:",
    featureOfflineAI: "प्रारंभिक सेटअप के बाद ऑफ़लाइन एआई निदान",
    featureRedFlags: "खतरे की महत्वपूर्ण संकेत चेतावनी",
    featureTriage: "ट्राइएज सिफारिशें",
    featureDrugInteraction: "दवा परस्पर क्रिया चेतावनियां",
    featureMultilingual: "बहुभाषी (अंग्रेजी, हिंदी और बांग्ला)",
    featurePatientRecords: "रोगी रिकॉर्ड प्रबंधन",
    
    // Authentication
    login: "लॉगिन",
    loginDescription: "सिस्टम तक पहुंचने के लिए अपनी जानकारी दर्ज करें",
    logout: "लॉगआउट",
    email: "ईमेल",
    password: "पासवर्ड",
    username: "उपयोगकर्ता नाम",
    fullName: "पूरा नाम",
    role: "भूमिका",
    userRole: "उपयोगकर्ता",
    adminRole: "प्रशासक",
    
    // Admin Panel
    createUser: "नया उपयोगकर्ता बनाएं",
    createUserDescription: "सिस्टम में एक नया स्वास्थ्य कार्यकर्ता जोड़ें",
    creating: "बनाया जा रहा है...",
    users: "उपयोगकर्ता",
    manageUsers: "स्वास्थ्य कार्यकर्ताओं को प्रबंधित करें",
    actions: "कार्रवाई",
    adminPanel: "प्रशासक पैनल",
  },
  bn: {
    appTitle: "এআই মেডিকেল ডায়াগনোসিস সহায়ক",
    appSubtitle: "গ্রামীণ স্বাস্থ্যসেবা সহায়তা সিস্টেম",
    
    // Navigation
    newPatient: "নতুন রোগী",
    diagnose: "নির্ণয়",
    history: "ইতিহাস",
    patients: "রোগী",
    
    // Patient Form
    patientRegistration: "রোগী নিবন্ধন",
    patientName: "রোগীর নাম",
    age: "বয়স",
    sex: "লিঙ্গ",
    male: "পুরুষ",
    female: "মহিলা",
    other: "অন্যান্য",
    weight: "ওজন (কেজি)",
    village: "গ্রাম",
    phone: "ফোন নম্বর",
    registerPatient: "রোগী নিবন্ধন করুন",
    
    // Diagnosis Form
    selectPatient: "রোগী নির্বাচন করুন",
    searchPatient: "রোগী অনুসন্ধান করুন...",
    symptoms: "লক্ষণ",
    symptomsPlaceholder: "লক্ষণগুলি বিস্তারিতভাবে বর্ণনা করুন (যেমন, জ্বর, কাশি, মাথাব্যথা, শরীরে ব্যথা...)",
    vitals: "গুরুত্বপূর্ণ চিহ্ন",
    temperature: "তাপমাত্রা (°F)",
    bloodPressure: "রক্তচাপ",
    systolic: "সিস্টোলিক",
    diastolic: "ডায়াস্টোলিক",
    spo2: "SpO2 (%)",
    pulse: "নাড়ি (bpm)",
    diagnoseNow: "এখন নির্ণয় করুন",
    analyzing: "বিশ্লেষণ করা হচ্ছে...",
    
    // Results
    diagnosisResults: "নির্ণয়ের ফলাফল",
    topDiagnoses: "শীর্ষ ডিফারেনশিয়াল ডায়াগনোসিস",
    confidence: "আত্মবিশ্বাসের স্তর",
    redFlags: "⚠️ বিপদ সতর্কতা",
    triageInstructions: "ট্রাইয়েজ নির্দেশাবলী",
    medications: "প্রস্তাবিত ওষুধ",
    contraindications: "প্রতিনির্দেশ এবং সতর্কতা",
    drugInteractionCheck: "ওষুধের পারস্পরিক ক্রিয়া পরীক্ষা",
    
    // Disclaimer
    disclaimer: "চিকিৎসা দাবিত্যাগ",
    disclaimerText: "এটি স্বাস্থ্যকর্মীদের জন্য একটি এআই-সহায়ক নির্ণয় সরঞ্জাম। এটি পেশাদার চিকিৎসা রায়ের বিকল্প নয়। সর্বদা যোগ্য চিকিৎসা কর্মীদের সাথে নির্ণয় এবং চিকিৎসা পরিকল্পনা যাচাই করুন। জরুরি অবস্থায়, অবিলম্বে উচ্চতর চিকিৎসা সুবিধায় রেফার করুন।",
    
    // Common
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল করুন",
    back: "ফিরে যান",
    next: "পরবর্তী",
    loading: "লোড হচ্ছে...",
    error: "ত্রুটি",
    success: "সফলতা",
    
    // Messages
    patientRegistered: "রোগী সফলভাবে নিবন্ধিত হয়েছে",
    diagnosisSaved: "নির্ণয় সফলভাবে সংরক্ষিত হয়েছে",
    errorOccurred: "একটি ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    noResultsFound: "কোনো ফলাফল পাওয়া যায়নি",
    
    // History
    encounterHistory: "এনকাউন্টার ইতিহাস",
    date: "তারিখ",
    diagnosis: "নির্ণয়",
    diagnoses: "নির্ণয়",
    viewDetails: "বিস্তারিত দেখুন",
    searchPatients: "রোগীর নাম, লক্ষণ বা গ্রাম দিয়ে অনুসন্ধান করুন...",
    noEncountersYet: "এখনও কোনো এনকাউন্টার রেকর্ড করা হয়নি",
    viewHistory: "ইতিহাস দেখুন",
    
    // Print
    printReport: "রিপোর্ট মুদ্রণ করুন",
    patientInformation: "রোগীর তথ্য",
    vitalSigns: "গুরুত্বপূর্ণ চিহ্ন",
    clinicalFindings: "ক্লিনিক্যাল ফলাফল",
    assessmentAndPlan: "মূল্যায়ন এবং পরিকল্পনা",
    medicalDisclaimer: "চিকিৎসা দাবিত্যাগ",
    generatedBy: "এআই মেডিকেল ডায়াগনোসিস সহায়ক দ্বারা তৈরি",
    dateTime: "তারিখ ও সময়",
    
    // Patient Profile
    patientProfile: "রোগীর প্রোফাইল",
    totalEncounters: "মোট এনকাউন্টার",
    viewProfile: "প্রোফাইল দেখুন",
    allEncounters: "সমস্ত এনকাউন্টার",
    
    // Home Page
    homeSubtitle: "গ্রামীণ স্বাস্থ্যকর্মীদের জন্য এআই-চালিত ডায়াগনস্টিক সহায়তা",
    homeDescription: "এই সিস্টেমটি সাধারণ গ্রামীণ স্বাস্থ্য পরিস্থিতির জন্য তাৎক্ষণিক ডায়াগনস্টিক সহায়তা, ট্রাইয়েজ সুপারিশ এবং চিকিৎসা নির্দেশিকা প্রদানের জন্য আপনার ব্রাউজারে স্থানীয়ভাবে চলমান উন্নত এআই মডেল ব্যবহার করে।",
    features: "বৈশিষ্ট্য:",
    featureOfflineAI: "প্রাথমিক সেটআপের পরে অফলাইন এআই ডায়াগনসিস",
    featureRedFlags: "বিপদ সংকেত গুরুত্বপূর্ণ চিহ্ন সতর্কতা",
    featureTriage: "ট্রাইয়েজ সুপারিশ",
    featureDrugInteraction: "ওষুধের পারস্পরিক ক্রিয়া সতর্কতা",
    featureMultilingual: "বহুভাষিক (ইংরেজি, হিন্দি এবং বাংলা)",
    featurePatientRecords: "রোগী রেকর্ড ব্যবস্থাপনা",
    
    // Authentication
    login: "লগইন",
    loginDescription: "সিস্টেম অ্যাক্সেস করতে আপনার পরিচয়পত্র লিখুন",
    logout: "লগআউট",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    username: "ব্যবহারকারীর নাম",
    fullName: "সম্পূর্ণ নাম",
    role: "ভূমিকা",
    userRole: "ব্যবহারকারী",
    adminRole: "প্রশাসক",
    
    // Admin Panel
    createUser: "নতুন ব্যবহারকারী তৈরি করুন",
    createUserDescription: "সিস্টেমে একজন নতুন স্বাস্থ্যকর্মী যোগ করুন",
    creating: "তৈরি হচ্ছে...",
    users: "ব্যবহারকারীগণ",
    manageUsers: "স্বাস্থ্যকর্মীদের পরিচালনা করুন",
    actions: "ক্রিয়া",
    adminPanel: "প্রশাসক প্যানেল",
  },
};

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.en;